export const getNhaKhoaSelector = state => state.nhaKhoa
export const getAuthSelector = state => state.auth
export const getNguoiLienHeSelector = state => state.nguoiLienHe
export const getBenhNhanSelector = state => state.benhNhan
export const getSanPhamSelector = state => state.sanPham
export const getQuyTrinhSelector = state => state.congDoan
export const getChamSocKhachHangSelector = state => state.chamSocKhachHang
export const getBangGiaSelector = state => state.bangGia
export const getDonHangSelector = state => state.donHang
export const getHoaDonSelector = state => state.hoaDon
export const getBaoCaoSelector = state => state.baoCao
export const getDashboardSelecor = state => state.dashboard
export const getNhanVienSelector = state => state.getNhanVienSelector
export const getBangLuongSelector = state => state.getBangLuongSelector
export const getChiPhiSelector = state => state.chiPhi